### ISSUE TITLE
Cannot record with streaming music?

### ISSUE THREAD

**Issue by nekohayo** [stickster/pulsecaster#1]
I tried PulseCaster in Fedora 21 and I think I'm hitting the same stumbling block as when I tried a year or two ago: I have a very simple test where I record my voice from my USB microphone, and then start a streaming radio in rhythmbox to cause audio activity on the "monitor" of my sound card output.

PulseCaster happily records and mixes the whole thing, but when I play the recorded .ogg file, it seems like the audio coming from Rhythmbox has been garbled/slowed down as if it was lagging.

Have you seen this before?

**Comment by stickster** [comment]
First, let me apologize for the unforgivably long lag in response time here. I haven't been able to reproduce this problem recently using Fedora 30 on x86_64. If you are still having this problem with the latest release, I hope you will do me the favor of letting me know. Please also tell me what OS and version you're using so I can try to reproduce the problem with the equipment I have available. Again, I'm sorry for the lack of response here and thank you for your bug report, because I do value your input.

**Comment by nekohayo** [comment]
You're all forgiven Paul, life happens! And I value the appreciation you have shown in your comment.

As the package has now trickled down into F31 updates but not 30 (and I'm not jumping on 31 just yet), I tried it again with `dnf install --releasever=31 --disablerepo=*fusion* --enablerepo="updates-testing" --nogpgcheck pulsecaster`

Good news: it seems the issue is gone in the new 0.9 release indeed. From the basic testing I did here today, there didn't seem to be anything blatantly wrong with the mixed recorded output. I will claim that you have secretly worked on this tirelessly for years to come up with the fix :)
